[package]
name = "board"
version = "0.1.0"
authors = ["Emil Gardström <emil.gardstrom@gmail.com>"]
description = "A (supposed) general purpose game board for tictac, renju, go and more!"
readme = "README.md"
license = "MIT"

[dependencies]
