[package]
name = "renju-board"
version = "0.1.0"
authors = ["Emil Gardström <emil.gardstrom@gmail.com>"]
description = "A WIP game board for renju designed in rust!"
readme = "README.md"
license = "MIT"
publish = false
edition = "2018"

[lib]
name = "renju"
path = "src/lib/lib.rs"
doctest = false

[[bin]]
name = "renju-board"
path = "src/bin/main.rs"

[profile.release] # Make sure to turn this off later
debug = true

[dependencies]
slog = "*"
slog-stdlog = "*"
daggy = "*"
num = "*"
nom = "*"
error-chain = "*"
clap = "*"
rustyline = "*"
